#FROM openjdk:8
FROM tomcat:8-jre8 
#EXPOSE 8080
COPY ./target/UserRegistration1-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps
WORKDIR /usr/local/tomcat/webapps
#CMD ["java", "-jar", "UserRegistration1-0.0.1-SNAPSHOT.jar"]

