From tomcat:8-jre8

# Maintainer 
MAINTAINER "sangeeta"
COPY home/ec2-user/jenkins/workspace/new-project/UserRegistration1/target/User-Registration-Login-SpringBoot-0.0.1-SNAPSHOT.jar /
WORKDIR /
CMD ["java", "-jar", "User-Registration-Login-SpringBoot-0.0.1-SNAPSHOT.jar"]

